# Generated by Django 2.1.2 on 2019-02-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergytype', models.CharField(max_length=256)),
                ('allergyagent', models.CharField(max_length=256)),
                ('allergyreaction', models.CharField(max_length=256)),
                ('reactionseverity', models.CharField(max_length=256)),
                ('allergyinfosource', models.CharField(max_length=256)),
                ('allergystatus', models.CharField(max_length=256)),
                ('allergyrecorddatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('doctortitle', models.CharField(max_length=256)),
                ('doctorfirstname', models.CharField(max_length=256)),
                ('doctorlastname', models.CharField(max_length=256)),
                ('specialty', models.CharField(max_length=256)),
                ('wardlocation', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardiantitle', models.CharField(blank=True, max_length=256)),
                ('guardianfirstname', models.CharField(blank=True, max_length=256)),
                ('guardianlastname', models.CharField(blank=True, max_length=256)),
                ('patientrelation', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('phonenumber', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunisationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinename', models.CharField(max_length=256)),
                ('vaccinedatetime', models.DateTimeField()),
                ('vaccinedose', models.CharField(max_length=256)),
                ('vaccinereason', models.CharField(max_length=256)),
                ('immunisationpriority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InjectionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injectionname', models.CharField(max_length=256)),
                ('injectiondatetime', models.DateTimeField()),
                ('injectionreason', models.CharField(max_length=256)),
                ('injectiondose', models.CharField(max_length=256)),
                ('injectionpriority', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationname', models.CharField(max_length=256)),
                ('medstartdatetime', models.DateTimeField()),
                ('medenddatetime', models.DateTimeField()),
                ('medicationduration', models.IntegerField()),
                ('medicationquantity', models.CharField(max_length=256)),
                ('medicationschedule', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NotesAndScans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.ImageField(default='default.png', upload_to='note_pics')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patienttitle', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=4)),
                ('patientfirstname', models.CharField(max_length=256)),
                ('patientlastname', models.CharField(max_length=256)),
                ('patientpreferredname', models.CharField(blank=True, max_length=256)),
                ('dateofbirth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'm'), ('F', 'f'), ('Other', 'o')], max_length=256)),
                ('weight', models.CharField(blank=True, max_length=256)),
                ('height', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('bmi', models.CharField(blank=True, max_length=256)),
                ('phonenumber', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('dnr', models.NullBooleanField()),
                ('wardlocation', models.CharField(blank=True, max_length=256)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('smoking', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=256)),
                ('drinking', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=256)),
                ('sexualorientation', models.CharField(blank=True, max_length=256)),
                ('socialdruguse', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=256)),
                ('handicaps', models.CharField(blank=True, max_length=256)),
                ('sexuallyactive', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=256)),
                ('personaldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('tablename', models.AutoField(primary_key=True, serialize=False)),
                ('tabledescription', models.CharField(max_length=256)),
                ('rowcount', models.IntegerField()),
                ('importdatadatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TableError',
            fields=[
                ('tablename', models.AutoField(primary_key=True, serialize=False)),
                ('tabledescription', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('errordescription', models.CharField(max_length=256)),
                ('importdatadatetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='notesandscans',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='medicationtable',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='injectiontable',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='immunisationtable',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='allergydetails',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
    ]
