# Generated by Django 2.1.2 on 2019-02-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousdiagnosis', models.CharField(max_length=256)),
                ('diagnoseddatetime', models.DateTimeField()),
                ('treatment', models.CharField(max_length=256)),
                ('treatmentdatetime', models.DateTimeField()),
                ('result', models.CharField(max_length=256)),
                ('personaldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allgergies', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('asthma', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('arthritis', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('glaucoma', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('cancer', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('tuberculosis', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('diabetes', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('hearttrouble', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('highbloodpressure', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('stroke', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('epilepsy', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('substanceabuse', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('depression', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('emotionalproblems', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('suicide', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('kidneytrouble', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('thyroiddisease', models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('personaldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='drinking',
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='drink',
            field=models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexuallyactive',
            field=models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexualorientation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='smoking',
            field=models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='socialdruguse',
            field=models.NullBooleanField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
    ]
