# Generated by Django 2.1.2 on 2019-04-03 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesandscans',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='notesandscans',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
    ]
