# Generated by Django 2.1.2 on 2019-02-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190226_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalEarlyWarningScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('respirationrate', models.CharField(blank=True, max_length=256)),
                ('oxygensaturation', models.CharField(blank=True, max_length=256)),
                ('systolicbloodpressure', models.CharField(blank=True, max_length=256)),
                ('levelofconsciousnessnewconfusion', models.CharField(blank=True, max_length=256)),
                ('temperature', models.CharField(blank=True, max_length=256)),
                ('personaldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyagent',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyinfosource',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyreaction',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergystatus',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergytype',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='reactionseverity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='immunisationtable',
            name='vaccinereason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='injectiontable',
            name='injectiondose',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='injectiontable',
            name='injectionpriority',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='injectiontable',
            name='injectionreason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='medicationtable',
            name='medenddatetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationtable',
            name='medicationduration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationtable',
            name='medicationquantity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='medicationtable',
            name='medicationschedule',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='medicationtable',
            name='medstartdatetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
