# Generated by Django 2.1.2 on 2019-02-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190226_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmunisationTable',
            new_name='Immunisation',
        ),
        migrations.RenameModel(
            old_name='InjectionTable',
            new_name='Injection',
        ),
        migrations.RenameModel(
            old_name='MedicationTable',
            new_name='Medication',
        ),
    ]
