# Generated by Django 2.1.2 on 2019-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190403_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergydetails',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnosishistory',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guardiandetails',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='immunisation',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='injection',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nationalearlywarningscore',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
    ]
