# Generated by Django 2.1.2 on 2019-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190403_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='lastmodified',
            field=models.DateField(auto_now=True),
        ),
    ]
