# Generated by Django 2.1.2 on 2019-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_personaldetails_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
    ]
