# Generated by Django 2.1.2 on 2019-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190226_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardiandetails',
            old_name='phonenumber',
            new_name='contactnumber',
        ),
    ]
