# Generated by Django 2.1.2 on 2019-04-04 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190403_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=256, verbose_name='Diagnosis')),
                ('symptons', models.CharField(max_length=256, verbose_name='Symptons')),
                ('previousdiagnosis', models.CharField(max_length=256, verbose_name='Previous Diagnosis')),
                ('diagnoseddatetime', models.DateTimeField(verbose_name='Diagnosis Date')),
                ('treatment', models.CharField(max_length=256, verbose_name='Treatment administered')),
                ('treatmentdatetime', models.DateTimeField(verbose_name='Treatment Date')),
                ('result', models.CharField(max_length=256)),
                ('lastmodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosishistory',
            name='personaldetails',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='allgergies',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='arthritis',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='depression',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='emotionalproblems',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='epilepsy',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='glaucoma',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='hearttrouble',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='kidneytrouble',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='substanceabuse',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='suicide',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='thyroiddisease',
        ),
        migrations.RemoveField(
            model_name='familyhistory',
            name='tuberculosis',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='eczma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Eczma'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='heartdisease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Heart Disease'),
        ),
        migrations.AddField(
            model_name='medication',
            name='route',
            field=models.CharField(blank=True, max_length=256, verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='city',
            field=models.CharField(default='', max_length=256, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.CharField(default='', max_length=256, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='county',
            field=models.CharField(default='', max_length=256, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='postcode',
            field=models.CharField(default='', max_length=256, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='bloodpressure',
            field=models.CharField(blank=True, max_length=256, verbose_name='Blood Pressure (mmHg)'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='heartrate',
            field=models.CharField(blank=True, max_length=256, verbose_name='Heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='oxygensaturation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Oxygen Saturation Levels (%)'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='respirationrate',
            field=models.CharField(blank=True, max_length=256, verbose_name='Respiration Rate (Breaths per minute)'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='temperature',
            field=models.CharField(blank=True, max_length=256, verbose_name='Temperature (c)'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 9 to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='DiagnosisHistory',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='personaldetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails'),
        ),
    ]
