# Generated by Django 2.1.2 on 2019-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190226_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdetails',
            name='sexualorientation',
            field=models.CharField(blank=True, choices=[('S', 'Straight'), ('G', 'Gay'), ('B', 'Bisexual')], max_length=10),
        ),
    ]
