# Generated by Django 2.1.2 on 2019-04-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190404_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='symptons',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.CharField(default='2', max_length=256, verbose_name='Symptoms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='previousdiagnosis',
            field=models.CharField(blank=True, max_length=256, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='result',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Treatment administered'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatmentdatetime',
            field=models.DateTimeField(blank=True, verbose_name='Treatment Date'),
        ),
    ]
