# Generated by Django 2.1.2 on 2019-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190226_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='respirationrate',
            field=models.CharField(blank=True, max_length=256, verbose_name='Respiration Rate'),
        ),
    ]
