# Generated by Django 2.1.2 on 2019-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190227_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyagent',
            field=models.CharField(blank=True, max_length=256, verbose_name='Allergy Agent'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyinfosource',
            field=models.CharField(blank=True, max_length=256, verbose_name='Allergy Info Source'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyreaction',
            field=models.CharField(blank=True, max_length=256, verbose_name='Allergy reaction'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergystatus',
            field=models.CharField(blank=True, max_length=256, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergytype',
            field=models.CharField(blank=True, max_length=256, verbose_name='Allergy type'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='reactionseverity',
            field=models.CharField(blank=True, max_length=256, verbose_name='Reaction severity'),
        ),
        migrations.AlterField(
            model_name='diagnosishistory',
            name='diagnoseddatetime',
            field=models.DateTimeField(verbose_name='Diagnosis Date'),
        ),
        migrations.AlterField(
            model_name='diagnosishistory',
            name='previousdiagnosis',
            field=models.CharField(max_length=256, verbose_name='Previous Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosishistory',
            name='treatment',
            field=models.CharField(max_length=256, verbose_name='Treatment administered'),
        ),
        migrations.AlterField(
            model_name='diagnosishistory',
            name='treatmentdatetime',
            field=models.DateTimeField(verbose_name='Treatment Date'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='allgergies',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='arthritis',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Arthritis'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='asthma',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Asthma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Cancer'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='depression',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Depression'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='emotionalproblems',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Emotional Problems'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='epilepsy',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Epilepsy'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='glaucoma',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Glaucoma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='hearttrouble',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Heart Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='highbloodpressure',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='High Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='kidneytrouble',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Kidney Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='stroke',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Stroke'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='substanceabuse',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Substance Abuse'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='suicide',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Suicide'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='thyroiddisease',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Thyroid Disease'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='tuberculosis',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Tuberculosis'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=256, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='email',
            field=models.CharField(blank=True, max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='guardianfirstname',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='guardianlastname',
            field=models.CharField(max_length=256, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='guardiantitle',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('SIR', 'Sir.')], max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='patientrelation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Patient Relation'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='immunisationpriority',
            field=models.IntegerField(verbose_name='Immunisation priority'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinedatetime',
            field=models.DateTimeField(verbose_name='Vaccine date administered'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinedose',
            field=models.CharField(max_length=256, verbose_name='Vaccine dose'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinename',
            field=models.CharField(max_length=256, verbose_name='Vaccine Name'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinereason',
            field=models.CharField(blank=True, max_length=256, verbose_name='Vaccine Reason'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectiondatetime',
            field=models.DateTimeField(verbose_name='Injection Date Administered'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectiondose',
            field=models.CharField(blank=True, max_length=256, verbose_name='Injection Dose'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectionname',
            field=models.CharField(max_length=256, verbose_name='Injection Name'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectionpriority',
            field=models.CharField(blank=True, max_length=256, verbose_name='Injection Priority'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectionreason',
            field=models.CharField(blank=True, max_length=256, verbose_name='Injection Reason'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medenddatetime',
            field=models.DateTimeField(blank=True, verbose_name='Medication End Date'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationduration',
            field=models.IntegerField(blank=True, verbose_name='Medication Duration'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationname',
            field=models.CharField(max_length=256, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationquantity',
            field=models.CharField(blank=True, max_length=256, verbose_name='Medication Quantity'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationschedule',
            field=models.CharField(blank=True, max_length=256, verbose_name='Medication Schedule'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medstartdatetime',
            field=models.DateTimeField(blank=True, verbose_name='Medication Start Date'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='levelofconsciousnessnewconfusion',
            field=models.CharField(blank=True, max_length=256, verbose_name='Level of Consciousness'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='oxygensaturation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Oxygen Saturation'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='systolicbloodpressure',
            field=models.CharField(blank=True, max_length=256, verbose_name='Systolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='temperature',
            field=models.CharField(blank=True, max_length=256, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='notesandscans',
            name='note_name',
            field=models.CharField(max_length=85, verbose_name='Note Description'),
        ),
        migrations.AlterField(
            model_name='notesandscans',
            name='notes',
            field=models.ImageField(upload_to='note_pics', verbose_name='Upload Note'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='bmi',
            field=models.CharField(blank=True, max_length=256, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dateofbirth',
            field=models.DateTimeField(verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dnr',
            field=models.NullBooleanField(verbose_name='DNR'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email',
            field=models.CharField(blank=True, max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'Other')], max_length=256, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='height',
            field=models.CharField(blank=True, max_length=256, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='patientfirstname',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='patientlastname',
            field=models.CharField(max_length=256, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='patientpreferredname',
            field=models.CharField(blank=True, max_length=256, verbose_name='Preferred name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='patienttitle',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('SIR', 'Sir.')], max_length=4, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=256, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='wardlocation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ward Location'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='weight',
            field=models.CharField(blank=True, max_length=256, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='drink',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Drinker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='handicaps',
            field=models.CharField(blank=True, max_length=256, verbose_name='Handicaps'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexuallyactive',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Sexually Active'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexualorientation',
            field=models.CharField(blank=True, choices=[('S', 'Straight'), ('G', 'Gay'), ('B', 'Bisexual')], max_length=10, verbose_name='Sexual Orientation'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='socialdruguse',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, verbose_name='Social Drug Use'),
        ),
    ]
