# Generated by Django 2.1.2 on 2019-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190227_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyagent',
            field=models.CharField(blank=True, choices=[('Propensity to adverse reaction (disorder)', 'Propensity to adverse reaction (disorder)'), ('Propensity to adverse reaction to drug (disorder)', 'Propensity to adverse reaction to drug (disorder)'), ('Propensity to adverse reaction to food (disorder)', 'Propensity to adverse reaction to food (disorder)'), ('Allergy to substance (disorder)', 'Allergy to substance (disorder)'), ('Drug allergy (disorder)', 'Drug allergy (disorder)'), ('Food allergy (disorder)', 'Food allergy (disorder)'), ('Drug intolerance (disorder)', 'Drug intolerance (disorder)'), ('Food intolerance (disorder)', 'Food intolerance (disorder)')], max_length=256, verbose_name='Allergy Agent'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergyinfosource',
            field=models.CharField(blank=True, choices=[('Practice Reported', 'Practice Reported'), ('Patient Reported', 'Patient Reported'), ('Allergy history', 'Allergy history'), ('Transition of care/referral', 'Transition of care/referral')], max_length=256, verbose_name='Allergy Info Source'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergystatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resolved', 'Resolved')], max_length=256, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='allergytype',
            field=models.CharField(blank=True, choices=[('Drug', 'Drug'), ('Food', 'Food'), ('Environmental', 'Environmental'), ('Inhalant', 'Inhalant'), ('Insect', 'Insect'), ('Plant', 'Plant'), ('Other', 'Other (Specify)')], max_length=256, verbose_name='Allergy type'),
        ),
        migrations.AlterField(
            model_name='allergydetails',
            name='reactionseverity',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=256, verbose_name='Reaction severity'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='allgergies',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='arthritis',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Arthritis'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='asthma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Asthma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Cancer'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='depression',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Depression'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='emotionalproblems',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Emotional Problems'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='epilepsy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Epilepsy'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='glaucoma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Glaucoma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='hearttrouble',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Heart Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='highbloodpressure',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='High Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='kidneytrouble',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Kidney Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='stroke',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Stroke'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='substanceabuse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Substance Abuse'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='suicide',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Suicide'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='thyroiddisease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Thyroid Disease'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='tuberculosis',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Tuberculosis'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='immunisationpriority',
            field=models.IntegerField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Requested', 'Requested')], verbose_name='Immunisation priority'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinename',
            field=models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis B', 'Hepatitis B'), ('Rotavirus', 'Rotavirus'), ('Diphtheria-Tetanus-Pertussis', 'Diphtheria-Tetanus-Pertussis'), ('Pneumococcal', 'Pneumococcal'), ('Poliovirus', 'Poliovirus'), ('Influenza', 'Influenza'), ('Measles-Mumps-Rubella', 'Measles-Mumps-Rubella'), ('Other', 'Other')], max_length=256, verbose_name='Vaccine Name'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectionpriority',
            field=models.CharField(blank=True, choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Requested', 'Requested')], max_length=256, verbose_name='Injection Priority'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationquantity',
            field=models.CharField(blank=True, max_length=256, verbose_name='Medication dose'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='drink',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Drinker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexuallyactive',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Sexually Active'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexualorientation',
            field=models.CharField(blank=True, choices=[('Hetrosexual', 'Hetrosexual'), ('homosexual', 'homosexual'), ('Bisexual', 'Bisexual')], max_length=10, verbose_name='Sexual Orientation'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='socialdruguse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Social Drug Use'),
        ),
    ]
