# Generated by Django 2.1.2 on 2019-03-19 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190319_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='patientuniqueid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Title'),
        ),
    ]
