# Generated by Django 2.1.2 on 2019-03-19 16:14

from django.db import migrations, models
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_personaldetails_patientuniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='patientuniqueid',
            field=models.CharField(default=mysite.utils.unique_patient_id_generator, max_length=10, unique=True, verbose_name='Title'),
        ),
    ]
