# Generated by Django 2.1.2 on 2019-03-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190319_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='patientuniqueid',
            field=models.CharField(max_length=10, unique=True, verbose_name='Title'),
        ),
    ]
