# Generated by Django 2.1.2 on 2019-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190319_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalearlywarningscore',
            name='levelofconsciousnessnewconfusion',
        ),
        migrations.RemoveField(
            model_name='nationalearlywarningscore',
            name='systolicbloodpressure',
        ),
        migrations.AddField(
            model_name='nationalearlywarningscore',
            name='bloodpressure',
            field=models.CharField(blank=True, max_length=256, verbose_name='Blood Pressure'),
        ),
        migrations.AddField(
            model_name='nationalearlywarningscore',
            name='bm',
            field=models.CharField(blank=True, max_length=256, verbose_name='Blood Monitoring Glucose (Diabetic)'),
        ),
        migrations.AddField(
            model_name='nationalearlywarningscore',
            name='heartrate',
            field=models.CharField(blank=True, max_length=256, verbose_name='Heart rate'),
        ),
        migrations.AlterField(
            model_name='immunisation',
            name='vaccinename',
            field=models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis A', 'Hepatitis A'), ('Hepatitis B', 'Hepatitis B'), ('Rotavirus', 'Rotavirus'), ('Diphtheria-Tetanus-Pertussis', 'Diphtheria-Tetanus-Pertussis'), ('Pneumococcal', 'Pneumococcal'), ('Poliovirus', 'Poliovirus'), ('Influenza', 'Influenza'), ('Measles-Mumps-Rubella', 'Measles-Mumps-Rubella'), ('Other', 'Other')], max_length=256, verbose_name='Vaccine Name'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medenddatetime',
            field=models.DateTimeField(verbose_name='Medication End Date'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medstartdatetime',
            field=models.DateTimeField(verbose_name='Medication Start Date'),
        ),
        migrations.AlterField(
            model_name='nationalearlywarningscore',
            name='oxygensaturation',
            field=models.CharField(blank=True, max_length=256, verbose_name='Oxygen Saturation Levels'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='patientuniqueid',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patient ID'),
        ),
    ]
