# Generated by Django 2.1.2 on 2019-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190320_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medicationduration',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicationquantity',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medicationschedule',
        ),
        migrations.AddField(
            model_name='medication',
            name='quantity',
            field=models.CharField(blank=True, max_length=256, verbose_name='Medication dose (mg)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='schedule',
            field=models.CharField(blank=True, max_length=256, verbose_name='Medication Schedule Frequency'),
        ),
        migrations.AddField(
            model_name='medication',
            name='usage',
            field=models.IntegerField(blank=True, choices=[('With Food', 'With Food'), ('Without Food', 'Without Food'), ('NA', 'NA')], default=1, verbose_name='Medication Usage'),
            preserve_default=False,
        ),
    ]
