# Generated by Django 2.1.2 on 2019-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190322_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunisation',
            name='immunisationpriority',
            field=models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('Requested', 'Requested')], max_length=9, verbose_name='Immunisation priority'),
        ),
    ]
