# Generated by Django 2.1.2 on 2019-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190322_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhistory',
            name='allgergies',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='arthritis',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Arthritis'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='asthma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Asthma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Cancer'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='depression',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Depression'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='emotionalproblems',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Emotional Problems'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='epilepsy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Epilepsy'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='glaucoma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Glaucoma'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='hearttrouble',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Heart Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='highbloodpressure',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='High Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='kidneytrouble',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Kidney Trouble'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='stroke',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Stroke'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='substanceabuse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Substance Abuse'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='suicide',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Suicide'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='thyroiddisease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Thyroid Disease'),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='tuberculosis',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Tuberculosis'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='drink',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Drinker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexuallyactive',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Sexually Active'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='sexualorientation',
            field=models.CharField(blank=True, choices=[('Hetrosexual', 'Hetrosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Prefer not to say', 'Prefer not to say')], max_length=17, verbose_name='Sexual Orientation'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='socialdetails',
            name='socialdruguse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], max_length=10, verbose_name='Social Drug Use'),
        ),
    ]
