# Generated by Django 2.1.2 on 2019-03-24 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190323_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patient',
            field=models.ManyToManyField(related_name='favorited_by', to='users.PersonalDetails'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injectiondose',
            field=models.CharField(blank=True, max_length=256, verbose_name='Injection Dose (ml)'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='usage',
            field=models.CharField(blank=True, choices=[('With Food', 'With Food'), ('Without Food', 'Without Food'), ('NA', 'NA')], max_length=12, verbose_name='Medication Usage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
