# Generated by Django 2.1.2 on 2019-03-25 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patient',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownwer', to=settings.AUTH_USER_MODEL),
        ),
    ]
