# Generated by Django 2.1.2 on 2019-03-25 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190325_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='patient',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
