# Generated by Django 2.1.2 on 2019-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_favouritepatient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favouritepatient',
            table='patient-favourite',
        ),
    ]
