# Generated by Django 2.1.2 on 2019-03-25 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_auto_20190325_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='favouritepatient',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='favouritepatient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='FavouritePatient',
        ),
    ]
