# Generated by Django 2.1.2 on 2019-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190325_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpatient',
            name='users',
            field=models.ManyToManyField(to='users.PersonalDetails'),
        ),
    ]
