# Generated by Django 2.1.2 on 2018-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('patientname', models.CharField(max_length=256)),
                ('dateofbirth', models.DateTimeField()),
                ('gender', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phonenumber', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=256)),
            ],
        ),
    ]
